version: "3.9"

services:
  database:
    image: postgres
    container_name: database_nlw
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: happy
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: happy
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
